Added several tests for Post request with search  it the body
informa-ibi/pharma-api-automation pull request #2
Opened 2022-06-24 11:23 UTC by mpushnikA1QA

2022-06-24 11:34 UTC, danil-shamsiev requested changes

2022-06-24 11:34 UTC, danil-shamsiev commented on src/test/steps/checkSinceQuery.js
> +const numberOfDates = 1;
Isn't it better to move this constant to constants? Also constants must have UPPER_CASE_SNAKE_CASE

2022-06-24 11:34 UTC, danil-shamsiev commented on src/test/steps/сheckSearchData.js
> +function deleteWildcardSearchingSymbol(str)
Move to String Utils

2022-06-24 11:34 UTC, danil-shamsiev commented on src/test/steps/сheckSearchData.js
> +const arrayTypeValue = 'array';
Array type is built into JS and it will most likely never change. So it would be better to get rid of this constant

2022-06-24 11:34 UTC, danil-shamsiev commented on src/constants/apiEndpoints.js
>  const authTokenEndpoint = "connect/token";
Constants must have UPPER_CASE_SNAKE_CASE

2022-06-24 11:34 UTC, danil-shamsiev commented on src/constants/dates.js
> +const datesArray = ["2000-12-05", "2021-10-17", "2022-05-17", "2021-01-01", "2012-08-23", "2014-09-29"]; //future time?
UPPER_CASE_SNAKE_CASE

2022-06-24 15:39 UTC, mpushnikA1QA commented on src/test/steps/checkSinceQuery.js
> +const numberOfDates = 1;
Fixed

2022-06-24 15:39 UTC, mpushnikA1QA commented on src/test/steps/сheckSearchData.js
> +function deleteWildcardSearchingSymbol(str)
Done

2022-06-24 15:40 UTC, mpushnikA1QA commented on src/constants/dates.js
> +const datesArray = ["2000-12-05", "2021-10-17", "2022-05-17", "2021-01-01", "2012-08-23", "2014-09-29"]; //future time?
Done

2022-06-25 09:48 UTC, danil-shamsiev approved these changes

2022-06-25 09:50 UTC, merged